services:
  kafka:
    image: apache/kafka:4.1.0
    container_name: fraud-kafka

    ports:
      - "29092:29092"
    
    volumes:
      - kafka-data:/tmp/kraft-combined-logs

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: >-
        PLAINTEXT://:9092,
        CONTROLLER://:9093,
        PLAINTEXT_HOST://:29092

      KAFKA_ADVERTISED_LISTENERS: >-
        PLAINTEXT://kafka:9092,
        PLAINTEXT_HOST://localhost:29092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: >-
        CONTROLLER:PLAINTEXT,
        PLAINTEXT:PLAINTEXT,
        PLAINTEXT_HOST:PLAINTEXT

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk

    healthcheck:
      test:
        - CMD
        - /opt/kafka/bin/kafka-topics.sh
        - --bootstrap-server
        - localhost:9092
        - --list
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  spark:
    image: >-
      apache/spark:4.0.1-scala2.13-java17-python3-ubuntu

    container_name: fraud-spark

    # Allows the local development container to write
    # dependency-cache and checkpoint files.
    user: "0:0"

    depends_on:
      kafka:
        condition: service_healthy

    volumes:
      - ./src:/opt/spark/work-dir/src:ro
      - spark-checkpoints:/tmp/spark-checkpoints
      - spark-ivy:/tmp/.ivy2

    command:
      - /opt/spark/bin/spark-submit
      - --master
      - "local[*]"
      - --conf
      - spark.jars.ivy=/tmp/.ivy2
      - --packages
      - >-
        org.apache.spark:spark-sql-kafka-0-10_2.13:4.0.1
      - >-
        /opt/spark/work-dir/src/streaming/spark_processor.py

volumes:
  kafka-data:
  spark-checkpoints:
  spark-ivy: