apiVersion: v1
kind: Service
metadata:
  name: fraud-api
  namespace: fraud-detection
spec:
  type: ClusterIP

  selector:
    app: fraud-api

  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP